[package]
name = "responder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.6"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "signal"] }
